/* eslint-disable no-console, max-len -- tooling script */
/*
 * Publishes the DA library sheets and icon previews generated by
 * tools/sidekick/build-block-library.js (run that first).
 *
 *   node tools/da/publish-library.js [--no-live]
 *
 * Uploads to Document Authoring (the site config's "library" tab points here):
 *   icons/*.svg                              -> /block-library/icons/<name>.svg (library previews)
 *   content/block-library/blocks.json        -> /block-library/blocks.json
 *   content/block-library/icons.json         -> /block-library/icons.json
 *   content/block-library/templates.json     -> /block-library/templates.json
 * then reads each back from DA and checks it matches, and previews (and, unless
 * --no-live, publishes) the three sheets. The icons used on pages are still served from
 * the code (/icons/<name>.svg); these copies only feed the library panel.
 */
const fs = require('node:fs');
const path = require('node:path');
const { curl, assertSafePage } = require('./publish-content.js');

const ROOT = process.cwd();
const DA_SOURCE = 'https://admin.da.live/source/nishant-gupta/1azee';
const LIB = path.join(ROOT, 'content', 'block-library');

function upload(file, daPath, type) {
  assertSafePage(daPath);
  const res = curl(['-X', 'POST', '-F', `data=@${file};type=${type}`, `${DA_SOURCE}/${daPath}`]);
  if (res.status >= 300) throw new Error(`${daPath}: upload HTTP ${res.status}`);
  const back = curl([`${DA_SOURCE}/${daPath}`]);
  const same = back.status === 200 && back.body().trim() === fs.readFileSync(file, 'utf8').trim();
  return { daPath, status: res.status, verified: same };
}

const results = [];
fs.readdirSync(path.join(ROOT, 'icons')).filter((f) => f.endsWith('.svg')).sort().forEach((f) => {
  results.push(upload(path.join(ROOT, 'icons', f), `block-library/icons/${f}`, 'image/svg+xml'));
});
const SHEETS = ['blocks.json', 'icons.json', 'templates.json'];
SHEETS.forEach((f) => {
  JSON.parse(fs.readFileSync(path.join(LIB, f), 'utf8')); // must be valid JSON
  results.push(upload(path.join(LIB, f), `block-library/${f}`, 'application/json'));
});

// Serve the sheets on preview (and live) too, like the pages that use them.
const ADMIN = 'https://admin.hlx.page';
const stages = process.argv.includes('--no-live') ? ['preview'] : ['preview', 'live'];
SHEETS.forEach((f) => stages.forEach((stage) => {
  const res = curl(['-X', 'POST', `${ADMIN}/${stage}/nishant-gupta/1azee/main/block-library/${f}`]);
  results.push({ daPath: `${stage} block-library/${f}`, status: res.status, verified: res.status === 200 });
}));

const bad = results.filter((r) => !r.verified);
console.log(`${results.length - bad.length}/${results.length} uploaded and verified in DA.`);
bad.forEach((r) => console.log(`  FAIL ${r.daPath} (upload ${r.status}, read-back mismatch)`));
process.exitCode = bad.length ? 1 : 0;
